### ISSUE TITLE
[BUG] Solution Components Mover doesn't Copy Custom APIs

### ISSUE THREAD

**Issue by ChrisGrohHS** [MscrmTools/MsCrmTools.SolutionComponentsMover#15] opened 2021-08-27 20:26 UTC
**Describe the bug**
The solutions component mover doesn't copy Custom APIs or their request/response parameters. 

componenttype:
10270 - Custom API
10271 - Custom API Request Parameter
10272 - Custom API Response Parameter

**To Reproduce**
Click to copy components. 

**Expected behavior**
The dialog should show an option for copying components. 

**Desktop (please complete the following information):**
 - XrmToolbox Version 1.2021.6.51
 - Tool version 1.2021.7.7

**Additional context**

**Comment by MscrmTools** [comment] 2021-08-30 07:46
Duplicate of #14

**Closed by MscrmTools** 2021-08-30 07:46 UTC
